---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginxdeployment
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./GitOps-For-Kubernetes/Section3/hands-on/withgitops/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginxdeployment
  targetNamespace: default

