---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginxdeployment
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default

