apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  namespace: default
  name: example-nginx
spec:
  chart:
    repository: https://charts.bitnami.com/bitnami/nginx
    version: 1.0.0
    name: bitnaminginx